

Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,


  File "/home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)


  File "/home/gitpod/.gitpod-code/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()


  File "/home/gitpod/.gitpod-code/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()

  File "/home/gitpod/.gitpod-code/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))

  File "/home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)

  File "/home/gitpod/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 239, in _get_code_from_file
  
    code = compile(f.read(), fname, 'exec')
  File "/workspace/M2-game-time/index.html", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

script.js:1 Failed to load resource: the server responded with a status of 404 ()




npm start
gitpod /workspace/M2-game-time $ npm start
Debugger attached.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /workspace/M2-game-time/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/workspace/M2-game-time/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-08-16T20_52_32_082Z-debug.log
Waiting for the debugger to disconnect...
gitpod /workspace/M2-game-time $ 